- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install PostgreSQL
  apt: pkg=postgresql-9.3 state=latest update_cache=true

- name: Restart PostgreSQL
  command: service postgresql restart

- name: create the postgresql user for application
  postgresql_user: name={{postgres_user}} password={{postgres_password}}
  sudo: yes
  sudo_user: postgres

- name: Create the postgresql database for application
  postgresql_db: name={{database_name}} owner={{postgres_user}} state=present
  sudo: yes
  sudo_user: postgres
